# Generated by Django 6.1 on 2026-09-02 08:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_rename_monthlysalary_monthlyincome'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlyincome',
            options={'ordering': ['-month', '-created_at'], 'verbose_name_plural': 'monthly incomes'},
        ),
        migrations.AlterUniqueTogether(
            name='monthlyincome',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='monthlyincome',
            name='source',
            field=models.CharField(blank=True, default='', help_text='e.g. Salary, Freelance, Bonus', max_length=100),
        ),
        migrations.AlterField(
            model_name='monthlyincome',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL),
        ),
    ]
