# Generated by Django 6.1 on 2026-09-02 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_monthlyincome_multi_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('quantity', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='expenses.expense')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
