# Generated by Django 6.1 on 2026-09-02 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensebreakdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensebreakdown',
            name='expense',
        ),
        migrations.CreateModel(
            name='BreakdownCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='expenses.expense')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='expensebreakdown',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='expenses.breakdowncluster'),
        ),
    ]
